---
- name: Create data directory
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    owner: 1001
    group: 1001
    mode: '0755'

- name: Create logs directory
  ansible.builtin.file:
    path: "{{ app_logs_dir }}"
    state: directory
    owner: 1001
    group: 1001
    mode: '0755'

- name: Pull application image
  community.docker.docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: pull
    force_source: yes

- name: Run bulletin-board container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{ bulletin_network_name}}"
    ports: "{{ app_ports }}"
    volumes:
      - "{{ app_data_dir }}{{ container_data_dir }}"
      - "{{ app_logs_dir }}:{{ container_logs_dir }}"
    env:
      JAVA_OPTS: "{{ java_opts | string }}"
      SPRING_PROFILES_ACTIVE: "{{ spring_profile | default('dev') | string }}"
      STORAGE_S3_BUCKET: "{{ storage_s3_bucket }}"
      STORAGE_S3_REGION: "{{ storage_s3_region }}"
      STORAGE_S3_ACCESSKEY: "{{ storage_s3_accesskey }}"
      STORAGE_S3_SECRETKEY: "{{ storage_s3_secretkey }}"
      STORAGE_S3_ENDPOINT: "{{ storage_s3_endpoint }}"
      STORAGE_S3_CDNURL: "{{ storage_s3_cdnurl }}"
      SPRING_DATASOURCE_URL: "{{ spring_datasource_url }}"
      SPRING_DATASOURCE_USERNAME: "{{ spring_datasource_username }}"
      SPRING_DATASOURCE_PASSWORD: "{{ spring_datasource_password }}"
    comparisons:
      "*": strict
