---
minio_image: "quay.io/minio/minio:latest"
minio_data_dir: "/var/minio/data"
minio_api_port: 9000
minio_console_port: 9001
minio_env_file: "/opt/minio/minio.env"
minio_bucket_name: "bulletin"
