---
minio_container_name: "minio"
minio_image: "quay.io/minio/minio:latest"
minio_data_dir: "/opt/minio/data"
minio_network_name: "bulletin-network"
#minio_bucket: "bulletin-board"
minio_ports:
        - "9000:9000"   # S3 API
        - "9001:9001"
minio_host: "minio"
minio_api_port: "9000"
storage_s3_bucket: "bulletins"
s3_region: "us-east-1"
s3_endpoint: "http://minio:9000"
s3_cdn_url:  "http://rdgw.kptech.ru:29000"